WITH_LINEAGE_CHARGER := false
BOARD_CHARGER_DISABLE_INIT_BLANK := true
BOARD_CHARGER_ENABLE_SUSPEND := false
BACKLIGHT_PATH := "/sys/class/leds/lcd-backlight/brightness"

TARGET_BOOTANIMATION_MULTITHREAD_DECODE := true
