# LG G4 Play Integrity identity

LG_BRAND=lge
LG_MANUFACTURER=LGE
LG_MODEL=LG-H815
LG_DEVICE=h815
LG_PRODUCT=h815_global_com

LG_BUILD_ID=NRD90U
LG_BUILD_INCREMENTAL=H81520p

LG_FINGERPRINT=lge/h815_global_com/h815:7.0/NRD90U/H81520p:user/release-keys
